// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PVAO.Infrastructure.Data;

namespace PVAO.Infrastructure.Migrations.IVDMS
{
    [DbContext(typeof(IVDMSContext))]
    partial class IVDMSContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PVAO.ApplicationCore.Entities.Security.Role", b =>
                {
                    b.Property<string>("userRole")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("userRole");

                    b.ToTable("vbms_role");
                });

            modelBuilder.Entity("PVAO.ApplicationCore.Entities.Security.User", b =>
                {
                    b.Property<string>("userName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("createdBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("dateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("divisionCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dockOff")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("lastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("modifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("passwordExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("userEnabled")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userRole")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userName");

                    b.ToTable("vbms_users");
                });

            modelBuilder.Entity("PVAO.ApplicationCore.Entities.Security.UserAccess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("BenefitU")
                        .HasColumnType("bit");

                    b.Property<bool?>("BenefitV")
                        .HasColumnType("bit");

                    b.Property<bool?>("Cancel")
                        .HasColumnType("bit");

                    b.Property<bool?>("NMonitoring")
                        .HasColumnType("bit");

                    b.Property<bool?>("PMonitoring")
                        .HasColumnType("bit");

                    b.Property<bool?>("Reassign")
                        .HasColumnType("bit");

                    b.Property<bool?>("UpdateBenefitStatus")
                        .HasColumnType("bit");

                    b.Property<bool?>("ValidationUpdates")
                        .HasColumnType("bit");

                    b.Property<bool?>("accruedC")
                        .HasColumnType("bit");

                    b.Property<bool?>("accruedU")
                        .HasColumnType("bit");

                    b.Property<bool?>("adminC")
                        .HasColumnType("bit");

                    b.Property<bool?>("adminD")
                        .HasColumnType("bit");

                    b.Property<bool?>("adminU")
                        .HasColumnType("bit");

                    b.Property<bool?>("adminV")
                        .HasColumnType("bit");

                    b.Property<bool?>("burialC")
                        .HasColumnType("bit");

                    b.Property<bool?>("burialU")
                        .HasColumnType("bit");

                    b.Property<bool?>("deathC")
                        .HasColumnType("bit");

                    b.Property<bool?>("deathU")
                        .HasColumnType("bit");

                    b.Property<bool?>("disabilityC")
                        .HasColumnType("bit");

                    b.Property<bool?>("disabilityU")
                        .HasColumnType("bit");

                    b.Property<bool?>("educationalC")
                        .HasColumnType("bit");

                    b.Property<bool?>("educationalU")
                        .HasColumnType("bit");

                    b.Property<bool?>("oldageC")
                        .HasColumnType("bit");

                    b.Property<bool?>("oldageU")
                        .HasColumnType("bit");

                    b.Property<string>("userRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("veteraninfoC")
                        .HasColumnType("bit");

                    b.Property<bool?>("veteraninfoU")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("vbms_useraccess");
                });
#pragma warning restore 612, 618
        }
    }
}
