// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PVAO.Infrastructure.Data;

namespace PVAO.Infrastructure.Migrations
{
    [DbContext(typeof(IVDMSContext))]
    [Migration("20210419051637_initial-migration")]
    partial class initialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PVAO.ApplicationCore.Entities.Structure.Bank", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("bankAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bankBranch")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bankCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bankName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("zipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("mdm_banks");
                });

            modelBuilder.Entity("PVAO.ApplicationCore.Entities.Structure.Beneficiary", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("currentAddress1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("currentAddress2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("currentAddress3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("currentZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("dateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dateOfDeath")
                        .HasColumnType("datetime2");

                    b.Property<string>("emailaddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("extensionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("middleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mortalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("placeOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("placeOfDeath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("relationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vdmsNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("claims_family");
                });

            modelBuilder.Entity("PVAO.ApplicationCore.Entities.Structure.Cheque", b =>
                {
                    b.Property<decimal?>("checkAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("checkNumber")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("checkRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("checkStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("checkType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("claimNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("dateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dateIssued")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dateRemitted")
                        .HasColumnType("datetime2");

                    b.ToTable("claims_checks");
                });

            modelBuilder.Entity("PVAO.ApplicationCore.Entities.Structure.ClaimApplication", b =>
                {
                    b.Property<string>("claimNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("benefitCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("dateApproved")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dateFiled")
                        .HasColumnType("datetime2");

                    b.Property<string>("firstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("middleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("referenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vdmsNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("claimNo");

                    b.ToTable("claims_applications");
                });

            modelBuilder.Entity("PVAO.ApplicationCore.Entities.Structure.Veteran", b =>
                {
                    b.Property<int>("vdmsno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("age")
                        .HasColumnType("int");

                    b.Property<string>("causeOfDeath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("currentAddress1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("currentAddress2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("currentAddress3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("currentZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("dateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dateModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dateOfDeath")
                        .HasColumnType("datetime2");

                    b.Property<string>("extensionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("middleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mortalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("placeOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("placeOfDeath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vfpOrganization")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("vdmsno");

                    b.ToTable("claims_veteran");
                });
#pragma warning restore 612, 618
        }
    }
}
